### ISSUE TITLE
adblock过滤列表可否通用?

### ISSUE THREAD

**Issue by hytd** [chenxsan/Privoxy#2]
你好,看到你的文章介绍,所以我想了解一下,adblock的过滤规则列表可否应用到privoxy上,因为我平常过滤广告使用的是adblock,如果可以通用的话这样就省去安装插件的资源了,这样启动firefox会更快

**Comment by chenxsan** [comment]
有不少这种把 adblock 规则转为 user.action 的工具，你可以看看 [http://andrwe.org/scripting/bash/privoxy-blocklist](http://andrwe.org/scripting/bash/privoxy-blocklist)，很早以前我用过这个，或者你也可以找找其它。

**Comment by hytd** [comment]
好的,感谢你的耐心解答
