### ISSUE TITLE
user.filter中g的用法问题

### ISSUE THREAD

**Issue by K1GP** [chenxsan/Privoxy#3]
在</body>这类只需要匹配一次的filter里不需要用g吧？
如：
`s@</head>@<link rel="stylesheet" type="text/css" href="http://p.p/user-manual/$host.css" />\n$0@D
`

另外可以配合用proxhttpsproxy过滤https。

**Comment by chenxsan** [comment]
是的，一次性的就不需要 `g` 了。

感谢推荐，我有空了解看看。
